from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
sentences = ["GARDENING MEGATHREAD! WE ARE NOW THE #1 GARDENING SUBREDDIT!",
             "PRAISE THE BEETROOT",
             "Should I post my bonsai tree this week?? I’m planning to trim the leaves before the flowers start growing again",
             "Beetroot was like a father to me",
             "Next week: Art!",
             "What the hell happened here?",
             "What should i grow?",
             "I haven't seen a single gardening meme, but I'm hoping cus it's only monday",
             "Been gone for 1 week and came to this what happen?",
             "I’ll ask the same question I asked on r/gardening How long is the interval between harvests for peppercorns?",
             "Yes it’s our lord and savior",
             "PAINTING WEEK! r/Pewdiepiesubmissions is now #1 painting subreddit with 2.5M subscribers!",
             "*Bob Ross week",
             "somebody shud keep pics of all these photos thats gonna be the subreddits profile pic fr evry theme",
             "Felix will return when this subs become GAMING WEEK at week 69",
             "BUT MY LEGO WEEK",
             "The icon hasn’t changed yet",
             "Id frick the pewdiepie reddit icon thingy",
             "We have achieved greatness",
             "What's next week?",
             "Do drawings count?",
             "When is Lego week?",
             "/r/PewdiepieSubmissions is now the biggest LEGO Subreddit! Post your lego memes this week!",
             "PewdiepieSubmissions has fallen into the river in LEGO city!",
             "Continue... A man",
             "Is the sub icon going to change?",
             "Imma post Bionicle memes.",
             "a redditor has fallen into the 'i don't have money' section of r/PewdiepieSubmissions",
             "Lego pewdiepie > baby yoda",
             "I need to make this",
             "Wow, I can’t believe that r/pewdiepiesubmissions is bigger than r/lego",
             "Must it be a Lego meme specifically? I have a couple MOCs that have the same aesthetic of Space Police III that I cannot tie into Memes!",
             "Whole sub going true jedi",
             "/r/Pewdiepiesubmissions is now the #1 Whiskey subreddit! Go wild!",
             "Let’s all get legless! Wait....",
             "u/sloth_on_meth deserves platnium for being a good mod",
             "I love underage drinking",
             "This subreddit is going to get banned for promoting underaged drinking",
             "Click here for the best wiskey in town",
             "LET'S GET FRICKING WASTED!!!!! Is what a irresponsible person would say, you can drink daily, but make sure it's a same amount and don't go overboard. Im doctor racer and this is my lesson today.",
             "Epic mod",
             "Whimskey",
             "r/whiskeygonewild",
             "PLEASE NO ACTUAL GONE WILD POSTS!",
             "It's TREBUCHET week! Throw your 90kg memes 300 meters !",
             "He’s not a gay mod. Impressive",
             "people who think catapults are better= small pp",
             "r/trebuchetmemes is gonna be happy",
             "Nice",
             "trebuchet>",
             "NEXT SHOULD BE YOYO WEEK!!!!(All caps cause I want people to see)",
             "Roses are red Water comes in liters A trebuchet can launch a 90 kg stone 300 meters",
             "The past tense of delete is",
             "Nothing sadder then spending hours making a working trebuchet with 3D cad software and creating a reddit account to post it and realizing you don’t meet the karma threshold so you can’t share it",
             "Mods Are Gay",
             "YoYo week part 2! Post your YoYo memes for another week!",
             "No im gonna post Jojo memes",
             "Post jojo memes my brothers",
             "Yo-Yo A JoJo!",
             "Ah yeah, YoYo's Bizarre Adventure everyone's favorite anime",
             "This is a battle tendency. I feel like there is a bloody stream in my body",
             "No",
             "It should be Why Is 2020 So Shitty Week",
             "Oh My God!!!",
             "I, Giorno Giovanna, am happy because of Jojo week",
             "When ur the second comment"]
analyzer = SentimentIntensityAnalyzer()
for sentence in sentences:
    vs = analyzer.polarity_scores(sentence)
    print("{:-<65} {}".format(sentence, str(vs)))
